### ISSUE TITLE
bin folder missing

### ISSUE THREAD

**Issue by flightcomp** [dandar3/android-androidx-lifecycle-viewmodel#1]
Errors occurred during the build.
Errors running builder 'Android Package Builder' on project '...'.
Resource '/.../bin' does not exist.

**Comment by dandar3** [comment]
@flightcomp 
I'm so sorry, I completely missed your issue. 

`bin` directory is not part of the source code, but should be created by Eclipse on first build. I would suggest using `Project` > `Build all` or or `Project` > `Clean` menu.
